### ISSUE TITLE
Random Numbers "259852417"

### ISSUE THREAD

**Issue by leisiamedeiros** [emergingcode/polyjuice#3]
I need create a fake to random numbers like CPF numbers or ID numbers for example. Or it should be something more generic like `Potions.Lorem.Characters(int length)` but that works for numbers.

**Comment by yanjustino** [comment]
@leisiamedeiros try use the [PTBR Identification](https://github.com/emergingcode/polyjuice/blob/master/Polyjuice/Potions/PtBr/Identification.cs) Class

**Comment by yanjustino** [comment]
An other way is Open the class [PolyjuiceNumerify](https://github.com/emergingcode/polyjuice/blob/master/Polyjuice/Extension/PolyjuiceNumerify.cs). This class is an extension that convert a sequence of  '#' (sharp) in number. 

eg : `"##########".Numerify()`

**Comment by leisiamedeiros** [comment]
Oks, thanks @yanjustino. I'll close the request and follow your advise.
